name: Deploy to Railway at 21 

on:
  schedule:
    - cron: '0 21 * * *'  # 20:00 UTC (22:00 ora italiana)
  workflow_dispatch:       # Permette trigger manuale

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: bot_telegram
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy and get ID
        run: |
          # Esegui il deploy
          railway up --service=${{ env.SVC_ID }}

          # Ottieni l'ultimo deployment ID
          DEPLOYMENT_ID=$(railway deployments --json | jq -r '.[0].id')
          echo "Deployment ID: $DEPLOYMENT_ID"

          # Salva ID e timestamp in un file
          echo '{"id": "'$DEPLOYMENT_ID'", "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"}' >> deployments.json

          # Commit e push del file
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployments.json
          git commit -m "Aggiungi deployment $DEPLOYMENT_ID"
          git push
