name: Railway Deploy & Undeploy

on:
  schedule:
    - cron: "25 16 * * *" # Deploy alle 20:00 (UTC 19 = Italia 20)
    - cron: "30 16 * * *"  # Undeploy alle 03:00 (UTC 2 = Italia 3)

jobs:
  deploy_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy bot
        if: github.event.schedule == '25 16 * * *'
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway up --service bot_telegram

      - name: Undeploy bot
        if: github.event.schedule == '30 16 * * *'
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway down --service bot_telegram
