name: Deploy Daily at 8PM

on:
  schedule:
    - cron: '25 0 * * *'  # 20:00 UTC (22:00 ora italiana)
  workflow_dispatch:       # Permette trigger manuale

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Service
        run: railway up --service bot_telegram
