name: Undeploy to Railway

on:
  schedule:
    - cron: '30 9 * * *'  # 20:00 UTC (22:00 ora italiana)
  workflow_dispatch:       # Permette trigger manuale
jobs:
  remove-deployment:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: bot_telegram
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Link Railway Project
        run: railway link ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Remove last deployment
        run: railway down --yes
