name: Error
on:
  schedule:
    - cron: '30 15 * * *'  # 20:00 UTC (21:00 ora italiana)
  workflow_dispatch:       # Permette trigger manuale
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: bot_telegram
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: errors
      - run: railway up --service=${{ env.SVC_ID }}
