name: Deploy with Intentional Failure to Stop Railway Service

on:
  workflow_dispatch:  # Permette il trigger manuale
  schedule:
    - cron: '0 2 * * *'  # Orario programmato

jobs:
  deploy-failure:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Deploy with Intentional Failure
        run: |
          # Fai un deploy intenzionale con errore (ad esempio, un errore nel codice)
          echo "Intentionally breaking the deployment"
          exit 1  # Forza un errore nell'Action, che blocca il deploy
