name: Undeploy Daily at 3AM

on:
  schedule:
    - cron: '28 0 * * *'   # 03:00 UTC (05:00 ora italiana)
  workflow_dispatch:       # Permette trigger manuale

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --help
        
      - name: Undeploy Service
        run: railway down --service bot_telegram
